### ISSUE TITLE
Set elasticsearch vm.max_map_count using nomad

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/node#177]
Could we use the [`sysctl`](https://www.nomadproject.io/docs/drivers/docker.html#sysctl) setting in nomad's docker driver to set this?

```hcl
config {
  sysctl {
    vm.max_map_count = "262144"
  }
}
```

cc @gabriel-v

**Comment by gabriel-v** [comment]
Yes, we want this because now we're shelling out to `sysctl` to validate the value on the host.

On debian this doesn't work, of course, since all interesting binaries are hidden:

```bash
gabriel@kowalski:/opt/liquid/node$ ./liquid deploy
Traceback (most recent call last):
  File "./liquid.py", line 71, in <module>
    main()
  File "./liquid.py", line 54, in main
    options.cmd(*extra_args)
  File "/opt/liquid/node/liquid_node/commands.py", line 227, in deploy
    check_system_config()
  File "/opt/liquid/node/liquid_node/commands.py", line 215, in check_system_config
    assert int(run("sysctl -n vm.max_map_count")) >= 262144, \
  File "/opt/liquid/node/liquid_node/process.py", line 14, in run
    return subprocess.check_output(cmd, **kwargs).decode('latin1')
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'sysctl -n vm.max_map_count' returned non-zero exit status 127.

gabriel@kowalski:/opt/liquid/node$ sysctl -n vm.max_map_count
-bash: sysctl: command not found
gabriel@kowalski:/opt/liquid/node$ sudo sysctl -n vm.max_map_count
262144
```

**Comment by gabriel-v** [comment]
setting limit from docker/nomad doesn't work - the keys are not working at all. these need to be set system-wide.
